version: '2'
services:
  team-server:
    container_name: team-server
    image: node:8.9
    working_dir: /usr/src/app/
    command: bash -c 'yarn install && yarn start'
    volumes:
      - ./:/usr/src/app/
    ports:
      - "3001:3001"
    depends_on:
      - dbmongo
      
  dbmongo: 
    image: mongo